version: '3.7'

services:

  postgres:
    image: 'postgres:12.1-alpine'
    
    env_file:
      - '.env'
    
    ports:
      - '$DB_PORT:5432'
    
    volumes:
      - postgres:/var/lib/postgresql/data
    
    networks:
      backend:
        aliases:
          - postgres

  pandazord:
    build: ./pandazord
    
    ports:
      - '$PANDAZORD_PORT:8000'
    
    env_file:
      - '.env'
    
    depends_on:
      - postgres
    
    networks:
      backend:
        aliases:
          - pandazord_backend

networks:
  backend:
    driver: bridge
  
volumes:
  postgres:
    driver: local
    name: postgres